---
name: Repo Dispatch Test

on:
  repository_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print event
      run: |
        echo Path: $GITHUB_EVENT_PATH
        echo cat $GITHUB_EVENT_PATH | jq .
...
